### ISSUE TITLE
Issue with GeoDataFrame

### ISSUE THREAD

**Issue by davehcdn** [tonymaranda/falaises_lidar#1]
Hello Tony,

I've spent hours getting this project working on my Macbook.  I have made a lot of notes and I would like to share them with the project in the future for setup.

I have successfully been able to resolve all the issues so far, but now I am getting into a technical issue with the Code which I want to ask you about.

Here is the error - There is a deprecation warning so I wonder if I am running newer versions than you are, or it is somehow related to the rtree?  It would be great to discuss on zoom or something so that we don't waste each other's time and can get straight to the point.  How should we exchange contact info?

```
Davids-MacBook-Pro:bin imac2015$ python3 ~/Documents/lidar/falaises_lidar-master/Main.py 
processing region 12...
total of 87 tiles to process
processing tile 21m08NE...
downloading file MNT_21m08NE.tif....
100% [..........................................................................] 7764010 / 7764010mnt disponible, processing.... 
1439
/Users/imac2015/Documents/lidar/falaises_lidar-master/Main.py:186: FutureWarning: Assigning CRS to a GeoDataFrame without a geometry column is now deprecated and will not be supported in the future.
  gdf = gpd.GeoDataFrame(mypoly, crs=raster.crs)
Traceback (most recent call last):
  File "/Users/imac2015/Documents/lidar/falaises_lidar-master/Main.py", line 190, in <module>
    gdf['surface'] = gdf['geometry'].area
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pandas/core/generic.py", line 5462, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'area'
```

**Comment by davehcdn** [comment]
Looks like Remi's fork of this project has a fix for this line: https://github.com/Marr11317/falaises_lidar/commit/18560c6c613a7dfce5bcb05857951d2f05c4bbdf

**Comment by ecstrema** [comment]
Did you manage to make it work?
I have a jupyter notebook that runs on Google colab if you prefer. My machine and internet were too slow for those gigabytes.

**Comment by davehcdn** [comment]
Yes, it was running all morning processing tiles, but then crapped out at the end when it couldn't locate carrieres.shp so I have to troubleshoot this, but it's getting further and at least it's "working".

I'm an azure web infrastructure node.js / DevOps admin so this python and particularly this geo stuff is totally new to me.  I also haven't used jupyter so you could always teach me about that too.

Maybe I'll reach back out to you if you are willing to show me how to create a much smaller custom area to scan so that I don't have to do so much processing in the future.

**Comment by ecstrema** [comment]
Like you, I didn't have any experience in all this geo stuff, but I found the documentation quite clear, and @tonymaranda had done all the work;)

Do you have an email adress so I can share with you the google colab script? It is presently formatted to work with regions, but if you want something smaller, it shouldn't difficult.

You can email me directly at remimarche@gmail.com for more infos.

**Comment by tonymaranda** [comment]
carrieres.shp is only a shapefile of all the quaries in Québec province
which. So you can get the shape on données ouvertes website or just ignore
those Lines, on this case your output Will include the quaries.

Cool to see you guys working on the script. I'm quitte busy with other
stuff at the moment but around mid feb I should be able to fix some Minor
issues.

Cheers!



Le ven. 22 janv. 2021 21 h 39, Rémi Marche <notifications@github.com> a
écrit :

**Comment by davehcdn** [comment]
@tonymaranda can you link to the shape file?  And the geol_simple.shp?  I looked in the .SHP package from the website but I didn't see them, I'll try look through more of the downloads.

@tonymaranda the best help I can think of will be to give me a tutorial on how to draw a custom shape / region to scan.  My hope is to use this to find boulders, and to do so I would want to tune it to be pretty sensitive, so I want to scan small areas where I suspect there to be boulders already...
